"""add deep ai usage tracking

Revision ID: e3f66ba23bb1
Revises: 6e2d73723723
Create Date: 2026-08-13 17:13:03.993813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f66ba23bb1'
down_revision: Union[str, Sequence[str], None] = '6e2d73723723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deep_ai_usage_id'), 'deep_ai_usage', ['id'], unique=False)
    op.create_index(op.f('ix_deep_ai_usage_user_id'), 'deep_ai_usage', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deep_ai_usage_user_id'), table_name='deep_ai_usage')
    op.drop_index(op.f('ix_deep_ai_usage_id'), table_name='deep_ai_usage')
    op.drop_table('deep_ai_usage')
    # ### end Alembic commands ###
